"""Inhalte für die Minispiele: Schätzfragen und Wörter zum Malen.

Schätzfragen: (Kategorie, Frage, Antwort, Einheit). „Jahr“ und „v. Chr.“ werden ohne Tausenderpunkt gezeigt.
Wo Quellen leicht abweichen oder Werte sich ändern, steht „etwa“ in der Frage – gewertet wird ohnehin, wer am
nächsten dran ist.
"""

CATEGORIES = {
    "alle": "Alle Themen",
    "welt": "Erde & Weltall",
    "natur": "Tiere & Natur",
    "koerper": "Mensch & Körper",
    "technik": "Technik & Erfindungen",
    "geschichte": "Geschichte",
    "sport": "Sport & Spiele",
    "alltag": "Alltag & Kultur",
    "deutschland": "Deutschland",
}

QUESTIONS = [
    # ------------------------------------------------------------------ Erde & Weltall
    ("welt", "Wie hoch ist der Mount Everest?", 8849, "m"),
    ("welt", "Wie hoch ist der K2, der zweithöchste Berg der Erde?", 8611, "m"),
    ("welt", "Wie viele Berge der Erde sind höher als 8.000 Meter?", 14, "Berge"),
    ("welt", "Wie hoch ist der Kilimandscharo, der höchste Berg Afrikas?", 5895, "m"),
    ("welt", "Wie hoch ist der Aconcagua, der höchste Berg Südamerikas?", 6961, "m"),
    ("welt", "Wie hoch ist der Denali, der höchste Berg Nordamerikas?", 6190, "m"),
    ("welt", "Wie hoch ist der Mont Blanc etwa?", 4806, "m"),
    ("welt", "Wie hoch ist der Großglockner, der höchste Berg Österreichs?", 3798, "m"),
    ("welt", "Wie hoch ist die Dufourspitze, der höchste Berg der Schweiz?", 4634, "m"),
    ("welt", "Wie weit ist der Mond im Durchschnitt von der Erde entfernt?", 384400, "km"),
    ("welt", "Wie weit ist die Sonne im Durchschnitt von der Erde entfernt?", 149600000, "km"),
    ("welt", "Wie viele Sekunden braucht das Licht von der Sonne bis zur Erde (etwa)?", 499, "Sekunden"),
    ("welt", "Wie viele Kilometer legt das Licht in einer Sekunde zurück (gerundet)?", 299792, "km"),
    ("welt", "Wie groß ist der Durchmesser der Erde im Mittel?", 12742, "km"),
    ("welt", "Wie lang ist der Erdumfang am Äquator?", 40075, "km"),
    ("welt", "Wie groß ist der Durchmesser des Mondes?", 3474, "km"),
    ("welt", "Wie groß ist der Durchmesser des Mars?", 6779, "km"),
    ("welt", "Wie groß ist der Durchmesser des Jupiters am Äquator?", 142984, "km"),
    ("welt", "Wie groß ist der Durchmesser der Sonne (etwa)?", 1392700, "km"),
    ("welt", "Wie viele Erdtage dauert ein Jahr auf dem Mars?", 687, "Tage"),
    ("welt", "Wie viele Erdtage dauert ein Jahr auf dem Merkur?", 88, "Tage"),
    ("welt", "Wie viele Erdtage braucht die Venus für eine Drehung um sich selbst?", 243, "Tage"),
    ("welt", "Wie viele Minuten dauert ein Tag auf dem Mars (24 h 37 min)?", 1477, "Minuten"),
    ("welt", "Wie viele Tage liegen zwischen zwei Vollmonden (etwa)?", 29.5, "Tage"),
    ("welt", "Wie alt ist die Erde (etwa)?", 4540000000, "Jahre"),
    ("welt", "Wie alt ist das Universum (etwa)?", 13800000000, "Jahre"),
    ("welt", "Wie viele Menschen sind bisher auf dem Mond herumgelaufen?", 12, "Menschen"),
    ("welt", "In welcher Höhe kreist die Raumstation ISS (etwa)?", 400, "km"),
    ("welt", "Wie viele Minuten braucht die ISS für eine Runde um die Erde (etwa)?", 92, "Minuten"),
    ("welt", "Wie viel Prozent der Erdoberfläche sind mit Wasser bedeckt (etwa)?", 71, "%"),
    ("welt", "Wie viel Prozent der Luft sind Sauerstoff (etwa)?", 21, "%"),
    ("welt", "Wie viel Prozent der Luft sind Stickstoff (etwa)?", 78, "%"),
    ("welt", "Wie viel Prozent des Wassers auf der Erde ist Süßwasser (etwa)?", 3, "%"),
    ("welt", "Wie viel Gramm Salz sind im Durchschnitt in einem Liter Meerwasser?", 35, "g"),
    ("welt", "Wie heiß ist die Oberfläche der Sonne (etwa)?", 5500, "°C"),
    ("welt", "Wie heiß ist ein Blitz (etwa)?", 30000, "°C"),
    ("welt", "Wie stark ist die Erdachse geneigt (etwa)?", 23.4, "Grad"),
    ("welt", "Wie lang ist der Nil (etwa)?", 6650, "km"),
    ("welt", "Wie lang ist der Amazonas (etwa)?", 6400, "km"),
    ("welt", "Wie lang ist die Wolga, der längste Fluss Europas?", 3530, "km"),
    ("welt", "Wie lang ist die Donau (etwa)?", 2850, "km"),
    ("welt", "Wie tief ist der Marianengraben an der tiefsten Stelle (etwa)?", 11000, "m"),
    ("welt", "Wie tief ist der Baikalsee, der tiefste See der Erde?", 1642, "m"),
    ("welt", "Wie hoch ist der Salto Ángel, der höchste Wasserfall der Erde?", 979, "m"),
    ("welt", "Wie groß ist die Sahara (etwa)?", 9200000, "km²"),
    ("welt", "Wie groß ist Grönland, die größte Insel der Erde (etwa)?", 2166000, "km²"),
    ("welt", "Wie groß ist Australien (etwa)?", 7690000, "km²"),
    ("welt", "Wie groß ist der Vatikanstaat?", 0.44, "km²"),
    ("welt", "Wie viele Staaten sind Mitglied der Vereinten Nationen?", 193, "Staaten"),
    ("welt", "Wie viele Staaten gibt es in Afrika?", 54, "Staaten"),
    ("welt", "Wie viele Bundesstaaten haben die USA?", 50, "Staaten"),
    ("welt", "Wie viele Kantone hat die Schweiz?", 26, "Kantone"),
    ("welt", "Wie viele Bundesländer hat Österreich?", 9, "Bundesländer"),
    ("welt", "Über wie viele Zeitzonen erstreckt sich Russland?", 11, "Zeitzonen"),
    ("welt", "Wie viele Menschen leben auf der Erde (2025, etwa)?", 8200000000, "Menschen"),
    ("welt", "Wie viele Sprachen werden auf der Erde gesprochen (etwa)?", 7000, "Sprachen"),
    ("welt", "Wie viele Jahre braucht der Halleysche Komet für eine Runde um die Sonne (etwa)?", 76, "Jahre"),
    ("welt", "In welchem Jahr wurde der Zwergplanet Pluto entdeckt?", 1930, "Jahr"),
    ("welt", "In welchem Jahr startete die Raumsonde Voyager 1?", 1977, "Jahr"),
    ("welt", "In welchem Jahr wurde das Hubble-Weltraumteleskop gestartet?", 1990, "Jahr"),
    ("welt", "In welchem Jahr startete das James-Webb-Weltraumteleskop?", 2021, "Jahr"),
    ("welt", "In welchem Jahr landeten zum ersten Mal Menschen auf dem Mond?", 1969, "Jahr"),
    ("welt", "In welchem Jahr flog Juri Gagarin als erster Mensch ins All?", 1961, "Jahr"),
    ("welt", "In welchem Jahr kreiste mit Sputnik der erste Satellit um die Erde?", 1957, "Jahr"),
    ("welt", "Wie heiß ist der Erdkern (etwa)?", 5500, "°C"),
    ("welt", "Wie viel Prozent Salz enthält das Tote Meer (etwa)?", 34, "%"),
    # ------------------------------------------------------------------ Tiere & Natur
    ("natur", "Wie lang kann ein Blauwal werden (etwa)?", 30, "m"),
    ("natur", "Wie viel wiegt das Herz eines Blauwals (etwa)?", 180, "kg"),
    ("natur", "Wie oft pro Minute kann das Herz eines tauchenden Blauwals nur noch schlagen (etwa)?", 2, "Schläge"),
    ("natur", "Wie oft pro Minute schlägt das Herz einer Maus (bis zu etwa)?", 600, "Schläge"),
    ("natur", "Wie hoch kann eine Giraffe werden (bis zu etwa)?", 6, "m"),
    ("natur", "Wie viel wiegt ein großer afrikanischer Elefantenbulle (etwa)?", 6000, "kg"),
    ("natur", "Wie viele Monate ist eine Elefantenkuh trächtig (etwa)?", 22, "Monate"),
    ("natur", "Wie viele Muskeln hat der Rüssel eines Elefanten (etwa)?", 40000, "Muskeln"),
    ("natur", "Wie schnell kann ein Gepard sprinten (etwa)?", 100, "km/h"),
    ("natur", "Wie viele Beine hat der Tausendfüßer-Rekordhalter, der 2021 in Australien gefunden wurde?", 1306, "Beine"),
    ("natur", "Wie viele Herzen hat ein Oktopus?", 3, "Herzen"),
    ("natur", "Wie viele Augen hat eine Honigbiene?", 5, "Augen"),
    ("natur", "Wie viele Zähne hat ein erwachsener Hund?", 42, "Zähne"),
    ("natur", "Wie viele Zähne hat eine erwachsene Katze?", 30, "Zähne"),
    ("natur", "Wie viel wiegt ein Straußenei (etwa)?", 1500, "g"),
    ("natur", "Wie oft pro Sekunde schlagen kleine Kolibris mit den Flügeln (bis zu etwa)?", 80, "Schläge"),
    ("natur", "Wie hoch ist Hyperion, der höchste bekannte Baum der Erde (ein Küstenmammutbaum)?", 116, "m"),
    ("natur", "Wie alt ist die Kiefer „Methusalem“ in Kalifornien (etwa)?", 4850, "Jahre"),
    ("natur", "Wie viele Käferarten sind bekannt (etwa)?", 400000, "Arten"),
    ("natur", "Wie viele Vogelarten gibt es auf der Erde (etwa)?", 11000, "Arten"),
    ("natur", "Wie viele Fledermausarten gibt es (etwa)?", 1400, "Arten"),
    ("natur", "Wie viele Eier legt ein Legehuhn im Jahr (etwa)?", 300, "Eier"),
    ("natur", "Wie viele Liter Milch gibt eine Kuh in Deutschland im Jahr (etwa)?", 8500, "Liter"),
    ("natur", "Wie tief kann ein Pottwal tauchen (bis zu etwa)?", 2000, "m"),
    ("natur", "Wie groß ist die Flügelspannweite eines Wanderalbatros (bis zu etwa)?", 3.5, "m"),
    ("natur", "Wie viele Apfelsorten gibt es weltweit (etwa)?", 7500, "Sorten"),
    ("natur", "Wie viele Beine hat eine Spinne?", 8, "Beine"),
    ("natur", "Wie viele Arme hat ein Seestern meistens?", 5, "Arme"),
    ("natur", "Wie viele Stunden am Tag schläft ein Koala (etwa)?", 20, "Stunden"),
    ("natur", "Riesenschildkröten können älter werden als … Jahre?", 150, "Jahre"),
    ("natur", "Wie lang ist ein ausgewachsener Eisbär (etwa)?", 2.5, "m"),
    ("natur", "Wie viele Kilometer legen Küstenseeschwalben auf ihrem Zug pro Jahr zurück (etwa)?", 70000, "km"),
    ("natur", "Wie viele Zähne hat ein erwachsenes Pferd (Hengst, meistens)?", 40, "Zähne"),
    ("natur", "Wie viele Wochen dauert es, bis aus einem Hühnerei ein Küken schlüpft?", 3, "Wochen"),
    ("natur", "Wie viele Tage ist eine Katze trächtig (etwa)?", 63, "Tage"),
    ("natur", "Grönlandwale können älter werden als … Jahre?", 200, "Jahre"),
    # ------------------------------------------------------------------ Mensch & Körper
    ("koerper", "Wie viele Knochen hat ein erwachsener Mensch?", 206, "Knochen"),
    ("koerper", "Wie viele Zähne hat ein Erwachsener mit Weisheitszähnen?", 32, "Zähne"),
    ("koerper", "Wie viele Milchzähne hat ein Kind?", 20, "Zähne"),
    ("koerper", "Wie viele Rippen hat ein Mensch?", 24, "Rippen"),
    ("koerper", "Wie oft schlägt das Herz eines Erwachsenen in Ruhe pro Minute (etwa)?", 70, "Schläge"),
    ("koerper", "Wie oft schlägt das Herz eines Menschen an einem Tag (etwa)?", 100000, "Schläge"),
    ("koerper", "Wie viele Liter Blut hat ein Erwachsener (etwa)?", 5, "Liter"),
    ("koerper", "Wie viel wiegt das Gehirn eines Erwachsenen (etwa)?", 1400, "g"),
    ("koerper", "Wie viele Nervenzellen hat das menschliche Gehirn (etwa)?", 86000000000, "Nervenzellen"),
    ("koerper", "Wie viele Haare hat ein Mensch auf dem Kopf (etwa)?", 100000, "Haare"),
    ("koerper", "Wie viele Zentimeter wachsen Kopfhaare im Monat (etwa)?", 1, "cm"),
    ("koerper", "Wie viel Prozent des Körpers eines Erwachsenen sind Wasser (etwa)?", 60, "%"),
    ("koerper", "Wie groß ist die Haut eines Erwachsenen (etwa)?", 1.8, "m²"),
    ("koerper", "Wie viele Muskeln hat der Mensch (etwa)?", 650, "Muskeln"),
    ("koerper", "Wie lang ist der Steigbügel im Ohr, der kleinste Knochen (etwa)?", 3, "mm"),
    ("koerper", "Wie viele Tage lebt ein rotes Blutkörperchen (etwa)?", 120, "Tage"),
    ("koerper", "Wie viele Wochen dauert eine Schwangerschaft (etwa)?", 40, "Wochen"),
    ("koerper", "Wie groß war Robert Wadlow, der größte Mensch, der je gemessen wurde?", 272, "cm"),
    ("koerper", "Wie alt wurde Jeanne Calment, der älteste Mensch mit sicherem Geburtsdatum?", 122, "Jahre"),
    ("koerper", "Welche Körpertemperatur ist beim Menschen normal (etwa)?", 37, "°C"),
    ("koerper", "Wie viele Liter Luft atmet ein Erwachsener in Ruhe pro Atemzug ein (etwa)?", 0.5, "Liter"),
    ("koerper", "Wie viele Geschmacksrichtungen kann die Zunge unterscheiden (süß, sauer …)?", 5, "Richtungen"),
    # ------------------------------------------------------------------ Technik & Erfindungen
    ("technik", "In welchem Jahr meldete Carl Benz sein Automobil zum Patent an?", 1886, "Jahr"),
    ("technik", "In welchem Jahr meldete Alexander Graham Bell das Telefon zum Patent an?", 1876, "Jahr"),
    ("technik", "In welchem Jahr gelang den Brüdern Wright der erste Motorflug?", 1903, "Jahr"),
    ("technik", "In welchem Jahr wurde das erste iPhone vorgestellt?", 2007, "Jahr"),
    ("technik", "In welchem Jahr schlug Tim Berners-Lee das World Wide Web vor?", 1989, "Jahr"),
    ("technik", "In welchem Jahr baute Konrad Zuse den Computer Z3?", 1941, "Jahr"),
    ("technik", "In welchem Jahr wurde die erste E-Mail verschickt?", 1971, "Jahr"),
    ("technik", "In welchem Jahr wurde die erste SMS verschickt?", 1992, "Jahr"),
    ("technik", "In welchem Jahr wurde das erste Gespräch mit einem Handy geführt?", 1973, "Jahr"),
    ("technik", "In welchem Jahr ließ James Watt seine Dampfmaschine patentieren?", 1769, "Jahr"),
    ("technik", "In welchem Jahr fuhr Karl Drais mit seiner Laufmaschine, dem Vorläufer des Fahrrads?", 1817, "Jahr"),
    ("technik", "In welchem Jahr fuhr die erste Eisenbahn in Deutschland (Nürnberg–Fürth)?", 1835, "Jahr"),
    ("technik", "Wie lang war die erste Eisenbahnstrecke Deutschlands, Nürnberg–Fürth (etwa)?", 6, "km"),
    ("technik", "In welchem Jahr erfand Alfred Nobel das Dynamit?", 1867, "Jahr"),
    ("technik", "In welchem Jahr entdeckte Wilhelm Conrad Röntgen die Röntgenstrahlen?", 1895, "Jahr"),
    ("technik", "In welchem Jahr entdeckte Alexander Fleming das Penicillin?", 1928, "Jahr"),
    ("technik", "In welchem Jahr veröffentlichte Einstein die spezielle Relativitätstheorie?", 1905, "Jahr"),
    ("technik", "Um welches Jahr druckte Gutenberg mit beweglichen Buchstaben (etwa)?", 1450, "Jahr"),
    ("technik", "In welchem Jahr fuhr der ICE zum ersten Mal planmäßig?", 1991, "Jahr"),
    ("technik", "In welchem Jahr landete der Mars-Rover Curiosity?", 2012, "Jahr"),
    ("technik", "Wie schnell ist der Schall in Luft bei 20 °C?", 343, "m/s"),
    ("technik", "Wie schnell fährt der ICE in Deutschland planmäßig höchstens?", 300, "km/h"),
    ("technik", "Wie hoch war die Mondrakete Saturn V (etwa)?", 111, "m"),
    ("technik", "Wie groß ist die Flügelspannweite eines Airbus A380 (etwa)?", 80, "m"),
    ("technik", "Wie lang war die Titanic (etwa)?", 269, "m"),
    ("technik", "Wie viele Tasten hat ein Klavier?", 88, "Tasten"),
    ("technik", "Wie viele Bit hat ein Byte?", 8, "Bit"),
    ("technik", "Wie viele Zeichen darf ein Beitrag auf X (früher Twitter) ohne Abo höchstens haben?", 280, "Zeichen"),
    ("technik", "Wie lang ist der Gotthard-Basistunnel (etwa)?", 57, "km"),
    ("technik", "Wie lang ist der Eurotunnel unter dem Ärmelkanal (etwa)?", 50, "km"),
    ("technik", "Wie viele Nieten halten den Eiffelturm zusammen (etwa)?", 2500000, "Nieten"),
    ("technik", "Wie viele VW Käfer wurden insgesamt gebaut (etwa)?", 21500000, "Autos"),
    ("technik", "In welchem Jahr wurde der Lego-Stein mit Noppen und Röhren patentiert?", 1958, "Jahr"),
    ("technik", "In welchem Jahr kam der Game Boy heraus?", 1989, "Jahr"),
    ("technik", "In welchem Jahr kam die erste PlayStation in Japan heraus?", 1994, "Jahr"),
    ("technik", "In welchem Jahr wurde Tetris erfunden?", 1984, "Jahr"),
    ("technik", "In welchem Jahr erschien Super Mario Bros. in Japan?", 1985, "Jahr"),
    ("technik", "In welchem Jahr erschien die Vollversion 1.0 von Minecraft?", 2011, "Jahr"),
    ("technik", "Wie viele Pokémon gab es in den ersten Spielen (Rot und Grün)?", 151, "Pokémon"),
    ("technik", "Wie viele Kilometer Autobahn gibt es in Deutschland (etwa)?", 13200, "km"),
    # ------------------------------------------------------------------ Geschichte
    ("geschichte", "In welchem Jahr erreichte Kolumbus Amerika?", 1492, "Jahr"),
    ("geschichte", "In welchem Jahr veröffentlichte Martin Luther seine 95 Thesen?", 1517, "Jahr"),
    ("geschichte", "In welchem Jahr begann die Französische Revolution?", 1789, "Jahr"),
    ("geschichte", "In welchem Jahr wurde Karl der Große zum Kaiser gekrönt?", 800, "Jahr"),
    ("geschichte", "In welchem Jahr endete das Weströmische Reich?", 476, "Jahr"),
    ("geschichte", "In welchem Jahr wurde die Unabhängigkeitserklärung der USA unterzeichnet?", 1776, "Jahr"),
    ("geschichte", "In welchem Jahr begann der Erste Weltkrieg?", 1914, "Jahr"),
    ("geschichte", "In welchem Jahr endete der Zweite Weltkrieg?", 1945, "Jahr"),
    ("geschichte", "In welchem Jahr landeten die Alliierten in der Normandie (D-Day)?", 1944, "Jahr"),
    ("geschichte", "In welchem Jahr begann der Dreißigjährige Krieg?", 1618, "Jahr"),
    ("geschichte", "Wie viele Jahre dauerte der Hundertjährige Krieg wirklich?", 116, "Jahre"),
    ("geschichte", "In welchem Jahr verlor Napoleon die Schlacht bei Waterloo?", 1815, "Jahr"),
    ("geschichte", "In welchem Jahr versank die Titanic?", 1912, "Jahr"),
    ("geschichte", "In welchem Jahr wurde das Grab des Tutanchamun entdeckt?", 1922, "Jahr"),
    ("geschichte", "In welchem Jahr nach Christus verschüttete der Vesuv die Stadt Pompeji?", 79, "Jahr"),
    ("geschichte", "Wann fanden die ersten Olympischen Spiele der Antike statt?", 776, "v. Chr."),
    ("geschichte", "Wann wurde Rom der Sage nach gegründet?", 753, "v. Chr."),
    ("geschichte", "Um wann wurde die Cheops-Pyramide gebaut (etwa)?", 2560, "v. Chr."),
    ("geschichte", "Wie hoch war die Cheops-Pyramide ursprünglich (etwa)?", 147, "m"),
    ("geschichte", "In welchem Jahr kehrte das Schiff der ersten Weltumsegelung (Magellan) zurück?", 1522, "Jahr"),
    ("geschichte", "In welchem Jahr wurde Mozart geboren?", 1756, "Jahr"),
    ("geschichte", "In welchem Jahr wurde Beethoven geboren?", 1770, "Jahr"),
    ("geschichte", "In welchem Jahr wurde Goethe geboren?", 1749, "Jahr"),
    ("geschichte", "In welchem Jahr wurde Albert Einstein geboren?", 1879, "Jahr"),
    ("geschichte", "In welchem Jahr wurde William Shakespeare geboren?", 1564, "Jahr"),
    ("geschichte", "Um welches Jahr begann Leonardo da Vinci die Mona Lisa (etwa)?", 1503, "Jahr"),
    ("geschichte", "In welchem Jahr wurden die ersten Nobelpreise verliehen?", 1901, "Jahr"),
    ("geschichte", "In welchem Jahr bekam Marie Curie als erste Frau einen Nobelpreis?", 1903, "Jahr"),
    ("geschichte", "In welchem Jahr wurden die Vereinten Nationen gegründet?", 1945, "Jahr"),
    ("geschichte", "In welchem Jahr wurden die Römischen Verträge (Gründung der EWG) unterzeichnet?", 1957, "Jahr"),
    ("geschichte", "In welchem Jahr fanden die ersten Olympischen Spiele der Neuzeit statt?", 1896, "Jahr"),
    ("geschichte", "In welchem Jahr wurde der Eiffelturm eröffnet?", 1889, "Jahr"),
    ("geschichte", "In welchem Jahr wurde mit dem Bau des Kölner Doms begonnen?", 1248, "Jahr"),
    ("geschichte", "In welchem Jahr wurde der Kölner Dom fertig?", 1880, "Jahr"),
    ("geschichte", "In welchem Jahr wurde mit dem Bau von Schloss Neuschwanstein begonnen?", 1869, "Jahr"),
    ("geschichte", "In welchem Jahr wurde die Brooklyn Bridge eröffnet?", 1883, "Jahr"),
    ("geschichte", "In welchem Jahr wurde der Suezkanal eröffnet?", 1869, "Jahr"),
    ("geschichte", "In welchem Jahr wurde der Panamakanal eröffnet?", 1914, "Jahr"),
    ("geschichte", "Wie lang ist die Chinesische Mauer mit allen Abschnitten (Vermessung 2012)?", 21196, "km"),
    # ------------------------------------------------------------------ Sport & Spiele
    ("sport", "Wie lang ist ein Marathon?", 42.195, "km"),
    ("sport", "Wie lang ist ein Fußballfeld nach FIFA-Empfehlung?", 105, "m"),
    ("sport", "Wie breit ist ein Fußballtor?", 7.32, "m"),
    ("sport", "Wie hoch ist ein Fußballtor?", 2.44, "m"),
    ("sport", "Wie hoch hängt ein Basketballkorb?", 3.05, "m"),
    ("sport", "Wie lang ist ein olympisches Schwimmbecken?", 50, "m"),
    ("sport", "Wie hoch ist der höchste Sprungturm bei Olympia?", 10, "m"),
    ("sport", "Welchen Durchmesser hat ein Tischtennisball?", 40, "mm"),
    ("sport", "Welchen Durchmesser hat ein Golfloch?", 108, "mm"),
    ("sport", "Wie viele Sekunden brauchte Usain Bolt für seinen 100-m-Weltrekord?", 9.58, "Sekunden"),
    ("sport", "Wie hoch ist der Weltrekord im Hochsprung der Männer (Sotomayor, 1993)?", 2.45, "m"),
    ("sport", "Wie weit ist der Weltrekord im Weitsprung der Männer (Mike Powell, 1991)?", 8.95, "m"),
    ("sport", "In welchem Jahr fand die erste Fußball-Weltmeisterschaft statt?", 1930, "Jahr"),
    ("sport", "Wie oft wurde die deutsche Männer-Nationalmannschaft Fußball-Weltmeister?", 4, "Titel"),
    ("sport", "In welchem Jahr startete die erste Saison der Fußball-Bundesliga?", 1963, "Jahr"),
    ("sport", "Wie viele Spieler einer Mannschaft stehen beim Rugby (Union) auf dem Feld?", 15, "Spieler"),
    ("sport", "Wie viele Spieler einer Mannschaft stehen beim Volleyball auf dem Feld?", 6, "Spieler"),
    ("sport", "Wie viele Minuten dauert ein Basketballspiel nach FIBA-Regeln (reine Spielzeit)?", 40, "Minuten"),
    ("sport", "Wie viele Minuten dauert ein Handballspiel (reine Spielzeit)?", 60, "Minuten"),
    ("sport", "Wie viele Felder hat ein Schachbrett?", 64, "Felder"),
    ("sport", "Wie viele Figuren stehen zu Beginn einer Schachpartie auf dem Brett?", 32, "Figuren"),
    ("sport", "Wie viele Felder hat ein Monopoly-Spielbrett?", 40, "Felder"),
    ("sport", "Wie viele Karten hat ein Skatspiel?", 32, "Karten"),
    ("sport", "Wie viele Augen hat ein normaler Würfel zusammen?", 21, "Augen"),
    ("sport", "Wie viele Ringe hat das olympische Symbol?", 5, "Ringe"),
    ("sport", "Wie viele Löcher hat ein normaler Golfplatz?", 18, "Löcher"),
    ("sport", "Wie viele Punkte bringt ein Touchdown im American Football?", 6, "Punkte"),
    ("sport", "Wie viele Kegel stehen beim Bowling?", 10, "Kegel"),
    ("sport", "Wie lang ist eine Bahn im Bowling von der Foullinie bis zum ersten Pin (etwa)?", 18.3, "m"),
    # ------------------------------------------------------------------ Alltag & Kultur
    ("alltag", "Wie viele Sekunden hat ein Tag?", 86400, "Sekunden"),
    ("alltag", "Wie viele Stunden hat eine Woche?", 168, "Stunden"),
    ("alltag", "Wie viele Minuten hat ein Jahr (ohne Schaltjahr)?", 525600, "Minuten"),
    ("alltag", "Wie viele Sekunden hat ein Jahr (ohne Schaltjahr)?", 31536000, "Sekunden"),
    ("alltag", "Wie viele Buchstaben hat das Alphabet (ohne Ä, Ö, Ü, ß)?", 26, "Buchstaben"),
    ("alltag", "Wie lang ist ein DIN-A4-Blatt?", 297, "mm"),
    ("alltag", "Wie breit ist ein DIN-A4-Blatt?", 210, "mm"),
    ("alltag", "Wie groß ist ein DIN-A0-Blatt?", 1, "m²"),
    ("alltag", "Wie breit ist eine Bankkarte im Scheckkartenformat?", 85.6, "mm"),
    ("alltag", "Wie viel wiegt eine 1-Euro-Münze?", 7.5, "g"),
    ("alltag", "Wie viel wiegt eine 2-Euro-Münze?", 8.5, "g"),
    ("alltag", "Wie viel wiegt eine 1-Cent-Münze?", 2.3, "g"),
    ("alltag", "Wie viele verschiedene Euro-Münzen gibt es?", 8, "Münzen"),
    ("alltag", "Wie viele Sterne sind auf der Europaflagge?", 12, "Sterne"),
    ("alltag", "Wie viele Sterne sind auf der Flagge der USA?", 50, "Sterne"),
    ("alltag", "Wie viele Kalorien haben 100 g Vollmilchschokolade (etwa)?", 530, "kcal"),
    ("alltag", "Wie viel Zucker ist in einem Liter Cola (etwa)?", 106, "g"),
    ("alltag", "Wie viele Liter Wasser verbraucht eine Person in Deutschland am Tag (etwa)?", 125, "Liter"),
    ("alltag", "Bei welcher Temperatur kocht Wasser auf Meereshöhe?", 100, "°C"),
    ("alltag", "Wie viele Bücher hat die Harry-Potter-Hauptreihe?", 7, "Bücher"),
    ("alltag", "Wie viele Sinfonien hat Beethoven geschrieben?", 9, "Sinfonien"),
    ("alltag", "Welche Nummer hat Mozarts Requiem im Köchelverzeichnis (KV)?", 626, "KV"),
    ("alltag", "Wie viele Sekunden dauert „Bohemian Rhapsody“ von Queen (Albumversion)?", 355, "Sekunden"),
    ("alltag", "In welchem Jahr erschien die erste Single der Beatles, „Love Me Do“?", 1962, "Jahr"),
    ("alltag", "In welchem Jahr erschien Michael Jacksons Album „Thriller“?", 1982, "Jahr"),
    ("alltag", "In welchem Jahr kam der erste Star-Wars-Film ins Kino?", 1977, "Jahr"),
    ("alltag", "In welchem Jahr kam der erste Harry-Potter-Film ins Kino?", 2001, "Jahr"),
    ("alltag", "In welchem Jahr kam „Toy Story“, der erste lange Pixar-Film, ins Kino?", 1995, "Jahr"),
    ("alltag", "In welchem Jahr erschien der Micky-Maus-Film „Steamboat Willie“?", 1928, "Jahr"),
    ("alltag", "Wie viele Saiten hat eine normale Gitarre?", 6, "Saiten"),
    ("alltag", "Wie viele Saiten hat eine Geige?", 4, "Saiten"),
    ("alltag", "Wie viele Tage hat ein Schaltjahr?", 366, "Tage"),
    ("alltag", "Wie viele Zentimeter hat ein Zoll?", 2.54, "cm"),
    ("alltag", "Wie viele Meter hat eine Meile (englische Landmeile, gerundet)?", 1609, "m"),
    ("alltag", "Wie viele Meter hat eine Seemeile?", 1852, "m"),
    ("alltag", "Wie viele Gramm wiegt ein Liter Wasser (etwa)?", 1000, "g"),
    # ------------------------------------------------------------------ Deutschland
    ("deutschland", "Wie hoch ist die Zugspitze?", 2962, "m"),
    ("deutschland", "Wie hoch ist der Brocken im Harz?", 1141, "m"),
    ("deutschland", "Wie hoch ist der Feldberg im Schwarzwald?", 1493, "m"),
    ("deutschland", "Wie hoch ist der Kölner Dom?", 157, "m"),
    ("deutschland", "Wie hoch ist der Turm des Ulmer Münsters, der höchste Kirchturm der Welt (etwa)?", 162, "m"),
    ("deutschland", "Wie hoch ist der Berliner Fernsehturm?", 368, "m"),
    ("deutschland", "Wie hoch ist das Brandenburger Tor (etwa)?", 26, "m"),
    ("deutschland", "Wie hoch ist der Commerzbank Tower in Frankfurt (ohne Antenne)?", 259, "m"),
    ("deutschland", "Wie groß ist Deutschland (etwa)?", 357600, "km²"),
    ("deutschland", "Wie viele Menschen leben in Deutschland (Ende 2024, etwa)?", 83600000, "Menschen"),
    ("deutschland", "Wie groß ist Berlin?", 891, "km²"),
    ("deutschland", "Wie groß ist der Bodensee?", 536, "km²"),
    ("deutschland", "Wie groß ist Rügen, die größte Insel Deutschlands (etwa)?", 926, "km²"),
    ("deutschland", "Wie lang ist der Rhein in Deutschland (etwa)?", 865, "km"),
    ("deutschland", "Wie lang ist der Rhein insgesamt (etwa)?", 1230, "km"),
    ("deutschland", "Wie lang ist die Elbe (etwa)?", 1094, "km"),
    ("deutschland", "Wie lang ist der Nord-Ostsee-Kanal (etwa)?", 98, "km"),
    ("deutschland", "An wie viele Länder grenzt Deutschland?", 9, "Länder"),
    ("deutschland", "Wie viele Bundesländer hat Deutschland?", 16, "Bundesländer"),
    ("deutschland", "Wie viele Abgeordnete hat der Bundestag seit der Wahl 2025?", 630, "Abgeordnete"),
    ("deutschland", "Wie viele Bundeskanzler(innen) hatte die Bundesrepublik bis einschließlich Friedrich Merz?", 10,
     "Personen"),
    ("deutschland", "Wie viele Jahre war Angela Merkel Bundeskanzlerin?", 16, "Jahre"),
    ("deutschland", "In welchem Jahr wurde das Grundgesetz verkündet?", 1949, "Jahr"),
    ("deutschland", "In welchem Jahr wurde die Berliner Mauer gebaut?", 1961, "Jahr"),
    ("deutschland", "In welchem Jahr fiel die Berliner Mauer?", 1989, "Jahr"),
    ("deutschland", "In welchem Jahr wurde Deutschland wiedervereinigt?", 1990, "Jahr"),
    ("deutschland", "In welchem Jahr gab es zum ersten Mal Euro-Bargeld?", 2002, "Jahr"),
    ("deutschland", "In welchem Jahr fand das erste Oktoberfest statt?", 1810, "Jahr"),
    ("deutschland", "In welchem Jahr wurde das Brandenburger Tor fertiggestellt?", 1791, "Jahr"),
    ("deutschland", "Wie viele Pkw waren in Deutschland 2024 zugelassen (etwa)?", 49000000, "Autos"),
]

# Wörter zum Malen – gut zu zeichnen, bekannt, eher kurz
WORDS = [
    "Haus", "Baum", "Sonne", "Mond", "Stern", "Wolke", "Regenbogen", "Blitz", "Schneemann", "Blume",
    "Pilz", "Kaktus", "Palme", "Apfel", "Banane", "Birne", "Kirsche", "Erdbeere", "Ananas", "Zitrone",
    "Karotte", "Tomate", "Pizza", "Burger", "Pommes", "Eis", "Torte", "Brezel", "Ei", "Käse",
    "Hund", "Katze", "Maus", "Elefant", "Giraffe", "Schlange", "Fisch", "Hai", "Wal", "Krake",
    "Schildkröte", "Schnecke", "Spinne", "Biene", "Schmetterling", "Vogel", "Eule", "Pinguin", "Huhn", "Ente",
    "Pferd", "Kuh", "Schwein", "Schaf", "Hase", "Igel", "Fuchs", "Bär", "Löwe", "Affe",
    "Frosch", "Krokodil", "Dinosaurier", "Drache", "Einhorn", "Qualle", "Krebs", "Marienkäfer", "Ameise", "Fledermaus",
    "Auto", "Bus", "Fahrrad", "Zug", "Flugzeug", "Hubschrauber", "Rakete", "Schiff", "U-Boot", "Traktor",
    "Ampel", "Brücke", "Leuchtturm", "Burg", "Zelt", "Iglu", "Kirche", "Pyramide", "Windmühle", "Riesenrad",
    "Brille", "Hut", "Krone", "Schuh", "Socke", "Hose", "Kleid", "Handschuh", "Regenschirm", "Rucksack",
    "Uhr", "Wecker", "Lampe", "Kerze", "Schlüssel", "Schloss", "Tür", "Fenster", "Treppe", "Leiter",
    "Stuhl", "Tisch", "Bett", "Sofa", "Badewanne", "Dusche", "Toilette", "Spiegel", "Kühlschrank", "Herd",
    "Tasse", "Teller", "Gabel", "Löffel", "Messer", "Pfanne", "Topf", "Flasche", "Glas", "Teekanne",
    "Buch", "Stift", "Schere", "Lineal", "Pinsel", "Radiergummi", "Brief", "Paket", "Geschenk", "Ballon",
    "Ball", "Fußball", "Tor", "Pokal", "Medaille", "Würfel", "Puzzle", "Drachen", "Kreisel", "Teddybär",
    "Gitarre", "Klavier", "Trommel", "Trompete", "Geige", "Mikrofon", "Kopfhörer", "Fernseher", "Handy", "Laptop",
    "Kamera", "Roboter", "Computer", "Tastatur", "Maus", "Batterie", "Glühbirne", "Magnet", "Lupe", "Mikroskop",
    "Hammer", "Säge", "Schraube", "Zange", "Schaufel", "Eimer", "Gießkanne", "Besen", "Staubsauger", "Waschmaschine",
    "Herz", "Auge", "Nase", "Mund", "Ohr", "Hand", "Fuß", "Zahn", "Knochen", "Skelett",
    "Pirat", "Ritter", "König", "Hexe", "Zauberer", "Gespenst", "Vampir", "Astronaut", "Clown", "Polizist",
    "Feuerwehr", "Krankenwagen", "Feuer", "Vulkan", "Berg", "Insel", "Strand", "Welle", "Wüste", "Höhle",
    "Anker", "Kompass", "Landkarte", "Schatz", "Flagge", "Kanone", "Schwert", "Schild", "Pfeil", "Bogen",
    "Weihnachtsbaum", "Osterei", "Kürbis", "Schneeflocke", "Tannenzapfen", "Blatt", "Gras", "Wurzel", "Nest", "Feder",
    "Zahnbürste", "Seife", "Handtuch", "Kamm", "Föhn", "Pflaster", "Spritze", "Thermometer", "Waage", "Sanduhr",
    "Ufo", "Alien", "Planet", "Satellit", "Komet", "Erde", "Sternschnuppe", "Rakete", "Mondlandung", "Teleskop",
    "Schaukel", "Rutsche", "Sandburg", "Trampolin", "Skateboard", "Rollschuh", "Ski", "Schlitten", "Surfbrett", "Angel",
    "Zebra", "Nashorn", "Nilpferd", "Känguru", "Koala", "Panda", "Faultier", "Papagei", "Flamingo", "Delfin",
    "Seepferdchen", "Muschel", "Seestern", "Krabbe", "Robbe", "Eisbär", "Wolf", "Hirsch", "Eichhörnchen", "Biber",
]
WORDS = list(dict.fromkeys(WORDS))  # doppelte Einträge nur einmal
